services:
  backend:
    build: backend
    
    ports:
      - 8000:8000

    volumes:
      - ./backend:/srv

  frontend:
    build: frontend

    environment:
      - VITE_API=http://localhost:8000

    ports: 
      - 80:80

    # volumes:
    #   - ./frontend:/srv

    depends_on:
      - backend